export declare const articleContent: string;
export declare const articleDate: string;
export declare const articleDefault: string;
export declare const backBtn: string;
export declare const images: string;
export declare const links: string;
export declare const rightPanel: string;
export declare const tags: string;
export declare const title: string;
